paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
#
# disqus: dbyll
#
title: You Space
email: henrique@htron-dev.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation of You-sapce.
baseurl: "you-space" # the subpath of your site, e.g. /blog
url: "https://hawk-developments.github.io/you-space/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zzHenryquezz
github_username:  zzhenryquezz
#
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

sass:
  sass_dir: _sass  
  style: compact

plugins:
  - jekyll-paginate

exclude: 
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  docs:
    output: true